/**
 * rules_ns.ts: o namespace `AuroraAPI.rules`, a base de conhecimento do yanc
 * (diretivas, palavras reservadas, mensagens do compilador e a tabela de
 * opcodes do assembly SAPHO).
 *
 * Saiu do js/api/aurora_api.js (item 13.3 do TODO). O `loadRules` tambem e
 * usado pela analise de .asm, e por isso e exportado.
 *
 * Compilado por `tsc` (npm run build:ts) num rules_ns.js ao lado, e esse .js
 * que o runtime carrega; os imports usam a extensao `.js`.
 */

import { ok, err } from './api_core.js';

/** Um opcode do assembly SAPHO, como o sync-sapho-rules o extrai do ASMComp.l. */
export interface OpcodeSapho {
  mnemonic: string;
  family?: string;
  [k: string]: unknown;
}

/** O resources/sapho_rules.json, so o que a API le. */
export interface RegrasDoSapho {
  directives?: Record<string, unknown>;
  language?: { keywords?: string[] };
  messages?: Array<{ code: string; [k: string]: unknown }>;
  asm?: { opcodes?: OpcodeSapho[] };
  [k: string]: unknown;
}

/* ============================================================
 *  rules, static yanc knowledge base
 *
 *  `resources/sapho_rules.json` is regenerated by
 *  `scripts/sync-sapho-rules.js` whenever the yanc source tree
 *  changes (see the script header for the why). The file is bundled
 *  with the installer, so the AI never depends on yanc being
 *  present on the user's machine.
 *
 *  Loaded lazily on first access, boot time stays unaffected if
 *  Aurora Intelligence is never opened.
 * ========================================================== */

let rulesPromise: Promise<RegrasDoSapho | null> | null = null;

/** O sapho_rules.json, carregado uma vez; null quando falta ou nao se le. */
export function loadRules(): Promise<RegrasDoSapho | null> {
  if (!rulesPromise) {
    rulesPromise = fetch('./resources/sapho_rules.json')
      .then((r) => (r.ok ? r.json() : null))
      .catch(() => null);
  }
  return rulesPromise;
}

export const rulesNs = {
  /** Full rules document. `null` if the file is missing. */
  async get() {
    return ok(await loadRules());
  },

  /** Look up a single hardware directive (case-insensitive: 'NBMANT'/'nbmant'). */
  async getDirective(name: unknown) {
    const rules = await loadRules();
    if (!rules?.directives) return err('rules not available');
    const key = String(name || '').replace(/^#/, '').toUpperCase();
    const hit = rules.directives[key];
    return hit ? ok(hit) : err(`unknown directive: ${name}`);
  },

  /** Names of all known hardware directives (e.g. ['NBMANT', 'NBEXPO', ...]). */
  async listDirectives() {
    const rules = await loadRules();
    return ok(rules?.directives ? Object.keys(rules.directives) : []);
  },

  /** Reserved language keywords (if/else/while/...). */
  async getKeywords() {
    const rules = await loadRules();
    return ok(rules?.language?.keywords ?? []);
  },

  /**
   * Look up a compiler message by its `MSG_*` code. Returns the
   * bilingual entry `{ code, severity, category, pt, en }`.
   */
  async lookupMessage(code: unknown) {
    const rules = await loadRules();
    const msg = rules?.messages?.find((m) => m.code === code);
    return msg ? ok(msg) : err(`unknown message code: ${code}`);
  },

  /**
   * Enumerate every SAPHO assembly opcode known to yanc, grouped by
   * family. Useful when the AI needs the full ISA at once (e.g. to
   * reason about which opcode pair would shrink a loop). Each entry
   * carries the numeric opcode, operand kind, family label, and the
   * one-line description scraped from ASMComp.l.
   */
  async listOpcodes() {
    const rules = await loadRules();
    return ok(rules?.asm?.opcodes ?? []);
  },

  /** Look up one opcode by mnemonic (case-insensitive). */
  async getOpcode(mnemonic: unknown) {
    const rules = await loadRules();
    if (!rules?.asm?.opcodes) return err('opcode table not available');
    const key = String(mnemonic || '').toUpperCase();
    const hit = rules.asm.opcodes.find((o) => o.mnemonic === key);
    return hit ? ok(hit) : err(`unknown opcode: ${mnemonic}`);
  },
};

