/**
 * gtkw_writer.js — Build a minimal GTKWave save-file (.gtkw) text from
 * a list of VCD scopes + an optional user selection.
 *
 * Pure: takes inputs, returns a string. The compilation flow handles
 * the actual disk write — keeping this module IO-free makes testing
 * trivial (feed scopes, assert text).
 *
 * Format kept intentionally minimal — `[dumpfile]` pointer + `@28`
 * (hex) header + one dotted-name per line. GTKWave fills in zoom /
 * position / etc. from defaults; the user can right-click inside
 * GTKWave to override any single trace's format. Anything fancier
 * means the user should curate their own .gtkw and import it via
 * Project Settings.
 */

/**
 * @typedef {{ name: string, path: string, signals: Array<{name, range, width, type}> }} VcdScope
 */

/**
 * Decide which scope.signal entries land in the save-file. Two modes:
 *   - selection non-empty: emit exactly those (skipping any that
 *     aren't in the VCD — covers "user picked then changed design").
 *   - selection empty: every signal at the testbench module's scope.
 *     Submodule signals are skipped; this matches the implicit
 *     `$dumpvars(1, <tb>)` default in the testbench instrumenter.
 *
 * @param {VcdScope[]} scopes
 * @param {string} tbModule
 * @param {string[]} selectedSignals
 * @returns {Array<{ fullName: string, range: string|null }>}
 */
export function pickSignalsToEmit(scopes, tbModule, selectedSignals) {
    const flatten = [];
    for (const scope of scopes) {
        for (const sig of scope.signals) {
            flatten.push({
                fullName: `${scope.path}.${sig.name}`,
                range: sig.range,
            });
        }
    }

    if (selectedSignals.length > 0) {
        const picks = new Set(selectedSignals);
        return flatten.filter((s) => picks.has(s.fullName));
    }

    return flatten.filter((s) => {
        const parts = s.fullName.split('.');
        return parts.length === 2 && parts[0] === tbModule;
    });
}

/**
 * Render the .gtkw file content.
 *
 * @param {object} input
 * @param {string} input.vcdPath        Absolute path to the .vcd, used
 *                                      verbatim in [dumpfile].
 * @param {string} input.gtkwPath       Absolute path the save-file
 *                                      will live at; written into
 *                                      [savefile] so GTKWave knows
 *                                      where it came from.
 * @param {VcdScope[]} input.scopes     Output of vcd_parser.
 * @param {string} input.tbModule       Testbench module name, used to
 *                                      pick the default top-scope set.
 * @param {string[]} [input.selectedSignals]  Picker selection.
 *                                            Empty = use default.
 * @returns {string|null}  Save-file text, or null if there's nothing
 *                         to display (no signals matched).
 */
export function buildGtkwContent({ vcdPath, gtkwPath, scopes, tbModule, selectedSignals = [] }) {
    if (!Array.isArray(scopes) || scopes.length === 0) return null;

    const toEmit = pickSignalsToEmit(scopes, tbModule, selectedSignals);
    if (toEmit.length === 0) return null;

    const slashed = (p) => p.replace(/\\/g, '/');
    const lines = [
        '[*]',
        '[*] Generated by Aurora',
        '[*]',
        `[dumpfile] "${slashed(vcdPath)}"`,
        `[savefile] "${slashed(gtkwPath)}"`,
        '[timestart] 0',
        '@28',
    ];
    for (const s of toEmit) {
        lines.push(s.range ? `${s.fullName}[${s.range}]` : s.fullName);
    }
    return lines.join('\n') + '\n';
}
