/**
 * gtkw_custom.js: escreve um .gtkw a partir de uma lista de sinais.
 *
 * O QUE ISTO NAO E
 * ----------------
 * Nao e o layout automatico. Aquele e o `buildAuroraGtkw` do
 * gtkw_proc_writer.ts, que le a hierarquia do dump, descobre os
 * processadores, escolhe cores, aliases e tradutores, e produz a curadoria
 * que o botao Wave abre sozinho. Ele precisa do dump para existir.
 *
 * Este e o caminho do pedido explicito: alguem (a pessoa ou a Aurora
 * Intelligence) sabe QUAIS sinais quer ver e em que ordem, e quer um arquivo
 * com exatamente isso. E o irmao do `createSurferLayout` do lado do GTKWave,
 * que faltava: dava para registrar um .gtkw que ja existia no disco, nunca
 * para criar um.
 *
 * O FORMATO
 * ---------
 * Os valores de flag vieram de um .gtkw salvo pelo proprio GTKWave, e nao de
 * adivinhacao, e por isso sao os mesmos do gtkw_proc_writer: uma divergencia
 * entre os dois faria o layout manual abrir com formatacao diferente do
 * automatico, no mesmo projeto. As flags valem em cascata ate a proxima linha
 * `@`, entao so se emite quando muda.
 *
 * Modulo puro, sem DOM e sem IPC: e onde o formato e testado.
 */

/** Flags de formato do GTKWave (ver gtkw_proc_writer.ts para a origem). */
const FLAGS = Object.freeze({
  bin: 0x28,      // TR_RJUSTIFY | TR_BIN
  dec: 0x24,      // TR_RJUSTIFY | TR_DEC
  signed: 0x420,  // TR_RJUSTIFY | TR_SIGNED
  hex: 0x22,      // TR_RJUSTIFY | TR_HEX
  real: 0x40020,  // TR_RJUSTIFY | TR_REAL
  ascii: 0x21,    // TR_RJUSTIFY | TR_ASCII
});

/** Linha de comentario, e abertura/fechamento de grupo recolhivel. */
const FLAG_COMMENT = 0x200;
const FLAG_GROUP_BEGIN = 0xC00200;
const FLAG_GROUP_END = 0x1401200;

/** Os nomes de base aceitos em `radix`. */
export const RADIX_VALIDOS = Object.freeze(Object.keys(FLAGS));

const hex = (n) => n.toString(16);

/**
 * Normaliza a entrada de um sinal.
 *
 * Aceita a forma curta (uma string com o caminho) e a completa (objeto), para
 * o caso comum ser uma lista de nomes e ninguem precisar aprender um formato
 * para pedir o obvio.
 */
function normalizar(entrada) {
  const bruto = typeof entrada === 'string' ? { path: entrada } : (entrada || {});
  const path = String(bruto.path || '').trim();
  if (!path) return null;
  const radix = String(bruto.radix || 'dec').toLowerCase();
  return {
    path,
    radix: Object.prototype.hasOwnProperty.call(FLAGS, radix) ? radix : 'dec',
    group: bruto.group ? String(bruto.group).trim() : null,
  };
}

/**
 * Monta o texto de um .gtkw com os sinais pedidos.
 *
 * @param {{
 *   signals: Array<string|{path:string, radix?:string, group?:string}>,
 *   dumpPath?: string|null,
 *   savePath?: string|null,
 *   title?: string|null,
 * }} entrada
 * @returns {{ conteudo: string, sinais: number, ignorados: string[] }}
 */
export function buildCustomGtkw({ signals, dumpPath = null, savePath = null, title = null } = {}) {
  const lista = Array.isArray(signals) ? signals : [];
  const ignorados = [];
  const limpos = [];
  for (const bruto of lista) {
    const s = normalizar(bruto);
    if (s) limpos.push(s);
    else ignorados.push(typeof bruto === 'string' ? bruto : JSON.stringify(bruto));
  }
  if (limpos.length === 0) {
    return { conteudo: '', sinais: 0, ignorados };
  }

  const linhas = ['[*]', '[*] Generated by Aurora', '[*]'];
  // O dump e o save sao opcionais de proposito. O caminho do dump so e
  // conhecido depois que a simulacao roda, e um layout escrito antes disso
  // continua valido: o GTKWave abre o arquivo que a AURORA passa na linha de
  // comando, e a chave [dumpfile] e uma conveniencia para quem abrir o .gtkw
  // direto, nao um requisito.
  if (dumpPath) linhas.push(`[dumpfile] "${dumpPath}"`);
  if (savePath) linhas.push(`[savefile] "${savePath}"`);
  linhas.push('[timestart] 0');

  if (title) {
    linhas.push(`@${hex(FLAG_COMMENT)}`);
    linhas.push(`-${title}`);
  }

  let flagAtual = null;
  let grupoAberto = null;
  const fecharGrupo = () => {
    if (grupoAberto === null) return;
    linhas.push(`@${hex(FLAG_GROUP_END)}`);
    linhas.push(`-${grupoAberto}`);
    flagAtual = FLAG_GROUP_END;
    grupoAberto = null;
  };

  for (const s of limpos) {
    // Grupo muda: fecha o anterior e abre o novo. Sinais sem grupo ficam
    // soltos no nivel de cima, que e onde o GTKWave os coloca.
    if (s.group !== grupoAberto) {
      fecharGrupo();
      if (s.group) {
        linhas.push(`@${hex(FLAG_GROUP_BEGIN)}`);
        linhas.push(`-${s.group}`);
        grupoAberto = s.group;
        flagAtual = FLAG_GROUP_BEGIN;
      }
    }
    const flag = FLAGS[s.radix];
    if (flag !== flagAtual) {
      linhas.push(`@${hex(flag)}`);
      flagAtual = flag;
    }
    linhas.push(s.path);
  }
  fecharGrupo();

  linhas.push('[pattern_trace] 1');
  linhas.push('[pattern_trace] 0');
  linhas.push('');
  return { conteudo: linhas.join('\n'), sinais: limpos.length, ignorados };
}
