import { describe, it, expect } from 'vitest';
import { extractSignalRefs } from '../../js/wave/gtkw_writer.ts';

describe('extractSignalRefs', () => {
    it('pulls dotted paths and strips trailing ranges', () => {
        const text = [
            '[*]',
            '[*] GTKWave Analyzer save file',
            '[dumpfile] "/tmp/tb.vcd"',
            '[savefile] "/tmp/tb.gtkw"',
            '@28',
            'tb_counter.clk',
            'tb_counter.q[3:0]',
            '-Group A',
            'tb_counter.dut.q_next[3:0]',
            '[group_close]',
        ].join('\n');
        expect(extractSignalRefs(text).sort()).toEqual([
            'tb_counter.clk',
            'tb_counter.dut.q_next',
            'tb_counter.q',
        ]);
    });

    it('ignores non-signal lines (decorations, comments, blank)', () => {
        const text = [
            '',
            '   ',
            '# a comment',
            '[*] header',
            '@1401200',
            '-MyGroup',
            '*another star',
            'tb.foo',
        ].join('\n');
        expect(extractSignalRefs(text)).toEqual(['tb.foo']);
    });

    it('rejects a bare identifier with no dot (not a hierarchical path)', () => {
        // A bare `clk` would mean module-less which Aurora's flow never
        // emits; if we see one, it's not something we can validate
        // against `tb_counter.<sig>` style VCD scopes.
        expect(extractSignalRefs('clk\ntb.dut.q')).toEqual(['tb.dut.q']);
    });

    it('returns an empty array for empty / non-string input', () => {
        expect(extractSignalRefs('')).toEqual([]);
        expect(extractSignalRefs(null)).toEqual([]);
        expect(extractSignalRefs(undefined)).toEqual([]);
    });

    it('dedupes repeated references', () => {
        const text = 'tb.clk\ntb.clk\ntb.q\n';
        expect(extractSignalRefs(text).sort()).toEqual(['tb.clk', 'tb.q']);
    });

    it('captures alias-prefixed signals (`+{alias} path[range]`)', () => {
        // buildAuroraGtkw emits these for Stack/ULA/typed vars
        // ("+{Data Stack Pointer} tb.proc.p_X.core.sp.pointeri[4:0]").
        // Before the fix, extractSignalRefs skipped them entirely
        // because the line didn't start with [a-zA-Z_], so a .gtkw
        // generated by Aurora itself appeared to have no signals.
        const text = [
            '@8420',
            '+{Data Stack Pointer} tb.proc.p_DTW.core.sp.pointeri[4:0]',
            '+{Assembly} tb.proc.valr2[31:0]',
            'tb.clk',
        ].join('\n');
        expect(extractSignalRefs(text).sort()).toEqual([
            'tb.clk',
            'tb.proc.p_DTW.core.sp.pointeri',
            'tb.proc.valr2',
        ]);
    });

    it('skips file/proc filter declarations (^N <path>, ^>N <path>)', () => {
        // Filter lines reference .txt/.exe paths on disk, not VCD
        // signals — never validate them as signal refs.
        const text = [
            '@2024',
            '^1 C:\\Temp\\ProcDTW\\trad_opcode.txt',
            '^>1 C:\\bin\\comp2gtkw.exe',
            'tb.clk',
        ].join('\n');
        expect(extractSignalRefs(text)).toEqual(['tb.clk']);
    });
});
