/**
 * O escritor de .gtkw sob encomenda (js/wave/gtkw_custom.js).
 *
 * Um .gtkw malformado nao da erro: o GTKWave abre e mostra menos sinais do que
 * se pediu, ou mostra todos com a base errada, e quem esta lendo a onda nao
 * tem como saber que o arquivo mentiu. Por isso o que se verifica aqui e o
 * texto exato, e nao "contem o nome do sinal".
 *
 * As flags sao as mesmas do layout automatico (gtkw_proc_writer). Se as duas
 * listas divergirem, o mesmo projeto abre com formatacao diferente conforme o
 * layout tenha sido gerado ou escrito a mao, e o teste de coerencia no fim
 * deste arquivo e o que impede isso.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { buildCustomGtkw, RADIX_VALIDOS } from '../../js/wave/gtkw_custom.js';

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

describe('buildCustomGtkw', () => {
  it('escreve cabecalho, sinais e rodape na forma que o GTKWave salva', () => {
    const { conteudo, sinais } = buildCustomGtkw({
      signals: ['tb.clk', 'tb.dut.acc'],
      dumpPath: 'C:\\p\\Temp\\tb.fst',
      savePath: 'C:\\p\\tb.gtkw',
    });
    expect(sinais).toBe(2);
    expect(conteudo.split('\n')).toEqual([
      '[*]',
      '[*] Generated by Aurora',
      '[*]',
      '[dumpfile] "C:\\p\\Temp\\tb.fst"',
      '[savefile] "C:\\p\\tb.gtkw"',
      '[timestart] 0',
      '@24',
      'tb.clk',
      'tb.dut.acc',
      '[pattern_trace] 1',
      '[pattern_trace] 0',
      '',
    ]);
  });

  it('emite a flag so quando a base muda, porque ela vale em cascata', () => {
    const { conteudo } = buildCustomGtkw({
      signals: [
        { path: 'tb.clk', radix: 'bin' },
        { path: 'tb.rst', radix: 'bin' },
        { path: 'tb.acc', radix: 'signed' },
      ],
    });
    const corpo = conteudo.split('\n').filter((l) => l.startsWith('@') || l.startsWith('tb.'));
    expect(corpo).toEqual(['@28', 'tb.clk', 'tb.rst', '@420', 'tb.acc']);
  });

  it('agrupa sinais consecutivos e fecha o grupo aberto no fim', () => {
    const { conteudo } = buildCustomGtkw({
      signals: [
        { path: 'tb.clk', radix: 'bin' },
        { path: 'tb.dut.x', group: 'DUT' },
        { path: 'tb.dut.y', group: 'DUT' },
      ],
    });
    const linhas = conteudo.split('\n');
    expect(linhas).toContain('@800200');
    expect(linhas).toContain('-DUT');
    // O fechamento existe e vem depois do ultimo sinal do grupo.
    expect(linhas.indexOf('@1000200')).toBeGreaterThan(linhas.indexOf('tb.dut.y'));
  });

  // O bit 0x400000 e o TR_CLOSED do GTKWave, e um grupo que o carrega abre
  // RECOLHIDO: na tela sobra o rotulo e nenhuma onda. Foi o que aconteceu com
  // a onda exportada do PRISM, que parecia ter falhado. Quem pede sinais por
  // nome quer ve-los, entao o padrao aqui e aberto; o recolhido continua
  // alcancavel para uma lista longa.
  it('o padrao e grupo ABERTO, e groupsOpen:false devolve o recolhido', () => {
    const sinais = [{ path: 'tb.dut.x', group: 'DUT' }];
    const aberto = buildCustomGtkw({ signals: sinais }).conteudo.split('\n');
    expect(aberto).toContain('@800200');
    expect(aberto).not.toContain('@c00200');

    const fechado = buildCustomGtkw({ signals: sinais, groupsOpen: false }).conteudo.split('\n');
    expect(fechado).toContain('@c00200');
    expect(fechado).toContain('@1401200');
  });

  it('base desconhecida cai em decimal em vez de escrever flag invalida', () => {
    const { conteudo } = buildCustomGtkw({ signals: [{ path: 'tb.x', radix: 'octal' }] });
    expect(conteudo).toContain('@24');
  });

  it('dump e save sao opcionais: o layout pode ser escrito antes da simulacao', () => {
    const { conteudo } = buildCustomGtkw({ signals: ['tb.x'] });
    expect(conteudo).not.toContain('[dumpfile]');
    expect(conteudo).not.toContain('[savefile]');
    expect(conteudo).toContain('[timestart] 0');
  });

  it('entrada vazia ou so com lixo devolve arquivo vazio, e diz o que ignorou', () => {
    expect(buildCustomGtkw({ signals: [] })).toMatchObject({ conteudo: '', sinais: 0 });
    const r = buildCustomGtkw({ signals: ['', '   ', null, { path: '' }] });
    expect(r.sinais).toBe(0);
    expect(r.ignorados.length).toBe(4);
  });

  it('sinal invalido no meio nao derruba os validos, e e relatado', () => {
    const r = buildCustomGtkw({ signals: ['tb.a', '', 'tb.b'] });
    expect(r.sinais).toBe(2);
    expect(r.ignorados).toEqual(['']);
    expect(r.conteudo).toContain('tb.a');
    expect(r.conteudo).toContain('tb.b');
  });
});

describe('coerencia com o layout automatico', () => {
  it('as flags de formato sao as mesmas do gtkw_proc_writer', () => {
    // Lidas do fonte porque la elas sao constantes internas, nao exportadas.
    // Compara-las aqui e o que impede o layout manual e o automatico
    // divergirem em silencio no mesmo projeto.
    const fonte = fs.readFileSync(path.join(RAIZ, 'js', 'wave', 'gtkw_proc_writer.ts'), 'utf8');
    const doWriter = {};
    for (const [nome, chave] of [['FMT_BIN', 'bin'], ['FMT_DEC', 'dec'], ['FMT_SIGNED_DEC', 'signed'], ['FMT_REAL', 'real']]) {
      const m = fonte.match(new RegExp(`const ${nome}\\s*=[^;]+;\\s*//\\s*(0x[0-9a-f]+)`, 'i'));
      expect(m, `${nome} nao encontrado com o valor anotado`).toBeTruthy();
      doWriter[chave] = parseInt(m[1], 16);
    }
    for (const [chave, valor] of Object.entries(doWriter)) {
      const { conteudo } = buildCustomGtkw({ signals: [{ path: 'tb.x', radix: chave }] });
      expect(conteudo, chave).toContain(`@${valor.toString(16)}`);
    }
  });

  it('a lista de bases aceitas e estavel e documentada', () => {
    expect([...RADIX_VALIDOS].sort()).toEqual(['ascii', 'bin', 'dec', 'hex', 'real', 'signed']);
  });
});
